sneako/finch

- lib/finch.ex
- lib/finch/conn.ex
- lib/finch/pool.ex
- lib/finch/pool_manager.ex
Basic error handling if the mint connection can't be established.
> Handle errors when mint can't connect

- LICENSE.md
- mix.exs
- add license
- update mix.exs hex metadata
> Prepare for 0.1.0 release

- lib/finch.ex
Causes dialyzer errors and conflicts with docs.
> fix typespec

- lib/finch.ex
- test/finch_test.exs
> Accepts a URI struct in request/3/4/5/6

- lib/finch/http1/pool.ex
> Revert "put back NimblePool.checkin"

- lib/finch/http1/conn.ex
- lib/finch/http1/pool.ex
> Revert "Remove transfer code and try peername"

- lib/finch/http1/conn.ex
- lib/finch/http1/pool.ex
This should fix the port leak too, but please verify.
> Another attempt at reducing transfer

- lib/finch/http2/pool.ex
- test/finch/http2/integration_test.exs
- test/support/http2_server.ex
Thanks to @bismark for noticing and providing the fix!
> Include query params in http2 requests

- lib/finch/http1/pool.ex
- lib/finch/telemetry.ex
- test/finch_test.exs
- also added a test for the `:reused_connection` event
> Add Telemetry event for max_idle_time_exceeded

- lib/finch/http2/pool.ex
It's possible to receive info messages in a disconnected state. This typically happens when we are in a read_only state but no longer have requests to wait on. If this occurs we preemptively move to a disconnected state and close the connection. But, in some scenarios its possible that we've already received the socket closed message in our inbox. This message causes the connection process to crash. While the connection process recovers correctly, it's better to not crash in this scenario.
> Add handle info call for the disconnected state

- test/finch_test.exs
I was using this test to check what the full `{:error, _}` tuple is when the pool times out & found that the assert in the catch wasn't being called.
This doesn't affect functionality at all, just fixing this test so it does get an exit there. I based the changes off of [this nimble_pool test](https://github.com/dashbitco/nimble_pool/blob/master/test/nimble_pool_test.exs#L280)
> Fix pool timeout test

- lib/finch.ex
Noticed a few minor spelling and formatting issues
> Misc doc updates

- lib/finch.ex
- lib/finch/error.ex
- lib/finch/http2/pool.ex
- test/finch/http2/pool_test.exs
Fixes https://github.com/keathley/finch/issues/142
> Add Finch.Error exception

- lib/finch/http2/request_stream.ex
- test/finch_test.exs
> fix handling of iodata in HTTP/2 request streams

- test/finch_test.exs
Continuing from https://github.com/sneako/finch/pull/158#commitcomment-62452183
> add failing test with iolist > window

- lib/finch/request.ex
> Finch.Request struct typespec

- lib/finch/http1/conn.ex
- lib/finch/http2/pool.ex
- test/finch_test.exs
> Add headers and status code to telemetry events

- CHANGELOG.md
- README.md
- lib/finch.ex
- lib/finch/http1/conn.ex
- lib/finch/http1/pool.ex
- lib/finch/http2/pool.ex
- lib/finch/telemetry.ex
- test/finch_test.exs
> Refactor telemetry events

- CHANGELOG.md
- lib/finch/request.ex
- test/finch_request_test.exs
- test/finch_test.exs
> Add support for private request metadata

- lib/finch.ex
> Do not use streams with async_request

- lib/finch/http2/pool.ex
> Update HTTP/2 pool log level to warning for retried action

- test/finch/http2/integration_test.exs
> Fix test: compare file size instead of map
