lib/finch.ex
lib/finch/conn.ex
test/finch_test.exs

During testing I noticed that my query string params were not being sent :)

Make sure we do not lose the request query string

---

lib/finch/pool.ex

Finch.Conn.request/3 only returns error tuples of the form: `{:error, %Conn{}, term}`

Remove unused error clause in Finch.Pool.request/3

---

lib/finch/conn.ex
lib/finch/response.ex
test/finch_test.exs

This resolves #5 
Thanks for making some issues on the repo! This issue seemed pretty trivial, so I thought I'd start here :)
I grabbed the typespecs from [Mint](https://github.com/elixir-mint/mint/blob/master/lib/mint/types.ex) to make sure they align with the types in `Finch.Response`.
I did not enforce any of the fields on the struct, because we receive the fields one at a time. If you'd like to enforce the fields on the struct, I'm happy to defer construction of the struct until we process the `:done` message.
In the case of `:data`, I defaulted to `""` because I think it makes for a cleaner API, but I understand if this is a controversial choice, and you'd prefer to be able to distinguish between an empty body, and no body.
Regardless, I'm happy to make any changes. I tried to stick …

Define Finch.Response and return it from Finch.request

---

.github/workflows/elixir.yml
README.md

Reduces build time from > 2 minutes, to ~30 seconds

CI caching

---

lib/finch.ex
lib/finch/pool_manager.ex
test/finch_test.exs

This resolves #7 
This is mostly a straightforward change. The most controversial decision is making `parse_and_normalize_url/1` return `{parsed_uri, shp}`. The reason I did this is to ensure that URLs are always parsed and normalized consistently, when being used to construct an `shp` tuple, but without requiring two parses when `Finch.request/5` is called.
I also raise an `ArgumentError` now when an invalid scheme is passed to `normalize_scheme/1`, so that we can return better errors on pool startup.

Change pools to be configured using URLs instead of shp tuples

---

lib/finch.ex
lib/finch/conn.ex
lib/finch/pool.ex
lib/finch/telemetry.ex
mix.exs
mix.lock
test/finch_test.exs

The current strategy works quite well if the server uses keep alive, however if the server does not, we see a significant performance degradation (even more than expected from the lack of keep alive).
If the server does not support keep alive or only allows a few requests per connection, all of our workers repeatedly have their connections closed, and reopened, which slows down our pool, and can also overwhelm the server. The problem gets worse with larger numbers of workers.
Instead, we can open the connections lazily, after giving it to the client. This gives the client better control over retries, and relieves pressure on the pool.
In my benchmarking, connecting lazily barely has an impact on throughput, if any at all, it only occurs when you first start using the pool, but once the …

Open connections lazily, in the client, rather than within the pool

---

lib/finch/conn.ex
lib/finch/pool.ex
lib/finch/telemetry.ex
test/finch_test.exs

Closes #27 
The issue mentions possibly tracking "first_use_time" separately, but I think this measurement alone should suit our needs for now.

Emit :handle_checkout events with idle_time measurements

---

lib/finch.ex
test/finch_test.exs

Closes #40 
Unfortunately, I don't think I can write a test for non standard HTTP methods using bypass, as the [Plug.Router](https://github.com/elixir-plug/plug/blob/8efb591f53c87c51a9aded8212daa78e7c3ff83e/lib/plug/router.ex#L47) only supports the standard ones.
Either way, we will need a new test server once we introduce HTTP/2 support, so I will begin looking in to a custom HTTP/1 test server now as well.

Allow arbitrary string methods to be used

---

lib/finch/http1/conn.ex
lib/finch/response.ex

So, after using starting to roll this out into production I've received a bunch of feedback that we should default the response body to an empty string. After thinking about it more I think that is probably the correct choice for a few reasons:
* It's not "wrong" semantically speaking. This is the most important point IMO. From the point of view of the parser, we'd expect it to return something like an empty string.
* It removes additional error checking logic that users need to do.
* There's a precedent for this in elixir already. The other clients return empty strings.
* Clients in other languages also use an empty string. I had only glanced at the ruby client. At this point, I'm pretty sure ruby is the outlier here.
That's my reasoning for making this change now.
TL;DR - @QuinnWilton …

Return empty string for missing response bodies

---

lib/finch/http1/pool.ex

Starting with OTP 23 `erlang:get_stacktrace/0` and thus `System.stacktrace/0` will always return an empty list.

Use __STACKTRACE__ instead of System.stacktrace()

---

README.md
lib/finch.ex
lib/finch/http1/conn.ex
lib/finch/http1/pool.ex
lib/finch/http2/pool.ex
lib/finch/pool.ex
lib/finch/request.ex
test/finch/http2/integration_test.exs
test/finch/http2/pool_test.exs
test/finch_test.exs

Both HTTP1 and HTTP2 already streamed internally,
this PR simply moves the stream out.
This PR also changed the main Finch API to have a
explicit step that builds the request. Instead of:
Finch.request(MyApp, :get, "/")
You must now do:
Finch.build(:get, "/") |> Finch.request(MyApp)
This is necessary otherwise the `Finch.stream/5`
API would be very complex. One advantage of this
approach is also that we no longer need to pass
empty headers when configuring get requests, for
example, instead of:
Finch.request(MyApp, :get, "/", [], nil, pool_timeout: 10_000)
One can now write:
Finch.build(:get, "/") |> Finch.request(MyApp, pool_timeout: 10_000)
The previous API has been properly deprecated.
Finally, this PR streamlines the `receive_timeout`
value. Previously the documentation and each pool …

Add streaming support

---

lib/finch/http1/conn.ex
lib/finch/telemetry.ex
test/finch_test.exs

So that metrics can be grouped by method where possible.
The method would be an uppercased string, which I think is appropriate for the use case.

Include http method in req and resp metrics

---

lib/finch/http2/pool.ex

The previous PR added `:method` to the `:request` Telemetry event, but only for http/1.
I started working on extracting the telemetry tests in finch_test.exs to a new file, and running them for both protocols, which brought to my attention several other inconsistencies. I'll open up a PR later on with that work.

add request method to h2 telemetry request metric as well

---

lib/finch/http1/conn.ex
lib/finch/http1/pool.ex

We don't need to transfer if we set the socket to passive mode.
The peername thing is just a guess based on hackney's code.

Remove transfer code and try peername

---

lib/finch/http1/pool.ex

We added the precheckin functionality to NimblePool to address a port leak here: https://github.com/keathley/finch/pull/31 and it was removed here: https://github.com/keathley/finch/pull/71
Unfortunately, without the precheckin, the port leak has returned
/cc @josevalim

put back NimblePool.checkin

---

lib/finch/http2/pool.ex

This PR adds metadata to the connection start event. This is going to be improved in some upcoming PRs. But it seemed like this was a useful fix to get out now.

Add metadata in connection start event

---

lib/finch.ex
lib/finch/http1/conn.ex
lib/finch/http1/pool.ex

Convert max_idle_time to native on init to
avoid doing conversions at runtime.
Also compute idle_time only once.

Reduce runtime time unit conversions

---

lib/finch.ex
lib/finch/http1/conn.ex
lib/finch/request.ex
test/finch_test.exs

This provides support for streaming request body with Elixir streams and Enumerable.reduce like @josevalim suggested.
I have tested this with fairly large files and it doesn't seem to be having any negative effect on memory with or without wrapping the streaming of body into Task.
@sneako suggested we *don't* do Task to to wrap streaming request body. @josevalim suggested we'd better wrap the whole operation in a process if we want to control the timeout on streaming request body.  Here is the conversation for reference: https://elixirforum.com/t/memory-leak-binaries-that-only-recon-bin-leak-1-helps-with/35804/10
I am, however, getting to conclusion that maybe we should *not* be handling that directly in Finch, and instead have a `timeout` parameter on …

Initial implementation of streaming request

---

lib/finch/telemetry.ex

The current indentation makes the rendered documentation look like:
The fix will make the first section look like the others. 
---
I verified it using an online markdown renderer:
With the fix:
Without the fix:

Fix formatting

---

lib/finch.ex

Hello!
I was using `stream/5` in a project today and noticed that the typespec appears to be incorrect. Currently `stream/5`'s [spec says it's return type is acc](https://github.com/keathley/finch/blob/v0.6.0/lib/finch.ex#L199). However, when using `stream/5` it returned `{:ok, acc}` instead. This appears to be confirmed in [existing Finch tests](https://github.com/keathley/finch/blob/v0.6.0/test/finch_test.exs#L667) for `stream/5`.
This PR updates the `stream/5` typespec to be `{:ok, acc}`. If I've missed something, please feel free to decline this PR and let me know!

Fix incorrect stream/5 typespec

---

lib/finch.ex
lib/finch/http1/conn.ex
mix.exs

I believe that this PR finally resolves the connection closed issues described in #62 and elsewhere. We've continued to see this issue in production. I added these flags to our pool configuration in production and we haven't seen a single issue for the past several hours. Based on the descriptions of the `keepalive` flag itself, I suspect we'll dramatically reduce the connection closed issues we've seen with finch.
As part of this fix I also defaulted the connect time to something much more reasonable (30 seconds is really way too high for a default) and enabled tcp nodelay. Everyone I know who has tuned http enables that flag (including us) so it makes sense to just set it as a default.
Lemme know what you think.

Add correct transport_opt flags to all pools

---

lib/finch.ex
lib/finch/request.ex
test/finch_test.exs

We had an issue the other day where a URL was malformed slightly. It was very hard to figure out what was failing and why. Adding a little more information to this error makes it much more obvious what is going wrong.

Return url in cast error

---

lib/finch.ex

Increase default HTTP1.1 pool size to 50 and include documentation about it.

---

lib/finch/pool_manager.ex
test/finch_test.exs

Hi @sneako 
As we discussed on https://github.com/elixir-mint/mint/pull/315 I am opening the equivalent PR on Finch. This will drop TLS options when `:default` configuration is used and the scheme is `:http` so that you can avoid getting `:badarg` error from Mint/gen_tcp.

Drop TLS options from conn_opts for http

---

lib/finch/request.ex

If I pass a request object with `query: ""`, I end up with a needless "?" appended to the path. I think `request_path/1` should also check for query being empty string. What do you think?

Stop appending empty query to path

---

lib/finch/http2/pool.ex

We don't demonitor the http connection when making http/2 requests. We need to do this in order to avoid memory leaks and build up of useless monitors.

Demonitor process when request is done

---

lib/finch.ex
lib/finch/http2/pool.ex
lib/finch/http2/request_stream.ex
test/finch_test.exs

closes #88
HTTP/2 streaming is quite a different beast from HTTP/1. The main catch is the control-flow, which is really a backpressure mechanism in which the server limits the number of bytes you can send on a per-connection and per-request-stream level. Once the window has been consumed, the server will replenish the window with a SETTINGS frame, allowing the client to send more data.
The approach we take here is to follow the [Mint documentation's recommendation](https://hexdocs.pm/mint/Mint.HTTP2.html#request/5-request-body-size) of switch from doing
```elixir
Mint.HTTP2.request(conn, method, path, headers, body)
```
to
```elixir
Mint.HTTP2.request(conn, method, path, headers, :stream)
```
for all non-nil `body`s. Then we use an …

HTTP/2: check window sizes, implement streaming

---

lib/finch/telemetry.ex

- Fixed a missing ending backtick which broke formatting
- Used backticks to highlight code items for clarity

Fix and improve Telemetry doc formatting

---

lib/finch/telemetry.ex

- Fix the other missing backtick I didn't spot in #185
- Remove colons and add newlines for consistency thoughout

Improve formatting of Telemetry docs (part 2)

---

test/finch/http1/pool_test.exs
test/finch/telemetry_test.exs
test/finch_test.exs
test/support/finch_case.ex

- introduce `FinchCase`
- use test name from context to provide a unique Finch :name
- extract all Telemetry tests to a new test file (we had multiple describe blocks for telemetry tests in the huge FinchTest file)

Test Refactor

---

lib/finch/http1/conn.ex
lib/finch/http1/mint_http1.ex
test/finch/http1/integration_proxy_test.exs
test/finch/http1/integration_test.exs
test/support/https1_server.ex

This adds several private proxy functions to Finch.HTTP1.Conn to dispatch to either Mint.UnsafeProxy or Mint.HTTP1. The dispatching is performed explicitly so as to better catch any changes to the underlying API with compiler errors/warnings where possible.
I don't think this completely finishes the scope of what was being discussed in #157 but it clears up the runtime errors and now handles HTTP 1.1 proxy configuration.

Add support for Mint.UnsafeProxy connections

---

lib/finch/http1/conn.ex
lib/finch/http2/pool.ex
test/finch_test.exs

It is unfortunate that we are building the list of headers twice in the case where the default streaming function is used, but I doubt the performance impact will be significant.
I am opening this as a draft while I test for performance regressions. Will report back here shortly.
cc @dvic 
Closes #192

accumulate headers and status code for telemetry events

---

lib/finch.ex
test/finch_test.exs

By default it will set the child_spec :id to the Finch :name. This
allows multiple Finch instances to be started under a single supervisor
without any additional configuration.
See https://github.com/phoenixframework/phoenix/issues/4876#issuecomment-1193323397 for discussion.
cc @wojtekmach

Define Finch.child_spec/1

---

mix.exs

CAStore 1.0 was released with no major API changes.
Alternatively the requirement could be just bumped to `1.0`.
I didn't update the `mix.lock` file, because `mint` also depends on `castore`, and because of some [changes](https://github.com/elixir-mint/mint/pull/331) tests would fail here after updating `mint`.

Allow using with castore 1.0

---

.github/workflows/elixir.yml
lib/finch.ex
test/finch_test.exs

There are some cases where I want to raise an exception on request failure. Instead of writing the `with` block every time or writing a helper function in my own code, it would be convenient to have a bang variation of `request`.
Let me know what you think. If this is accepted, it would be great if you could also cut a release after merging so I could start using the new function. Thanks!

Add request! function

---

lib/finch/http2/pool.ex

Closes #213 
By replying with this error, the client will no longer hang when the conditions described in the issue are met.
Sorry for the delay @Goose97. I tested this change with your bug reproduction repo and can confirm that the client no longer hangs forever in this scenario.

http/2: reply to cancel requests in disconnected state

---

lib/finch/http2/pool.ex
test/finch/http1/telemetry_test.exs
test/finch/http2/telemetry_test.exs

Emit `:send` and `:recv` telemetry for HTTP2 async requests

---

.github/workflows/elixir.yml
lib/finch/http2/pool.ex
mix.exs

I'm not sure if this is the right way. Maybe it's also possible to bump the minimum Elixir version to 1.11? But I guess that would be a breaking change :/

Fix calls to deprecated Logger.warn/2

---

.github/workflows/elixir.yml
mix.lock

List of changes:
- Bump x509 dep (0.8.3 => 0.8.7), see https://github.com/voltone/x509/pull/60
- Bump Elixir (1.14.5 => 15.1.1) and GitHub Actions
```sh
$ mix test
==> file_system
Compiling 7 files (.ex)
Generated file_system app
==> mime
Compiling 2 files (.ex)
Generated mime app
==> x509
Compiling 22 files (.ex)
warning: Logger.warn/1 is deprecated. Use Logger.warning/2 instead
lib/x509/test/suite.ex:585: X509.Test.Suite.sni_handler/2
warning: Logger.warn/1 is deprecated. Use Logger.warning/2 instead
lib/x509/test/crl_server.ex:110: X509.Test.CRLServer.flush_headers/3
== Compilation error in file lib/x509/asn1.ex ==
** (UndefinedFunctionError) function :epp_dodger.parse_file/1 is undefined (module :epp_dodger is not available)
:epp_dodger.parse_file(~c"/home/foobar/.asdf/installs/erlang/ …
```

Resolve compilation issue with Elixir 1.15

---

.github/workflows/elixir.yml

We have `mix deps.compile` and `mix compile` steps and before this patch
they were running in the default env, :dev, resulting in unnecessary
compilations.

Set MIX_ENV=test on CI

---

lib/finch.ex
lib/finch/http1/conn.ex
lib/finch/http2/pool.ex
lib/finch/response.ex
test/finch/http1/integration_test.exs
test/finch/http1/telemetry_test.exs
test/finch_test.exs
test/support/mock_socket_server.ex

Ref https://github.com/wojtekmach/req/issues/230#issue-1869352131
I couldn't write an integration test for http2 given Plug has no support for trailers and it is not easy to write a fake server.
I verified it manually:
```
$ openssl req -newkey rsa:2048 -nodes -keyout server.key -x509 -days 365 -out server.crt
$ cat main.go
```
```go
package main
import (
"log"
"net/http"
)
func main() {
srv := &http.Server{Addr: ":8080", Handler: http.HandlerFunc(handle)}
log.Printf("Serving on https://0.0.0.0:8080")
log.Fatal(srv.ListenAndServeTLS("server.crt", "server.key"))
}
func handle(w http.ResponseWriter, r *http.Request) {
log.Printf("Got connection: %s", r.Proto)
w.Header().Set("trailer", "x-foo")
w.Write([]byte("Hello"))
w.Header().Set("x-foo", "bar")
}
```
```
$ cat run.exs
```
```elixir …
```

Split trailers from headers

---

lib/finch.ex
lib/finch/http1/conn.ex
lib/finch/http1/pool.ex
test/finch_test.exs

Intended to timeout a request with a chunked response after the total elapsed time has surpassed the given value. See #243.

Introduce :request_timeout option

---

lib/finch.ex
lib/finch/http1/conn.ex
lib/finch/http1/pool.ex
lib/finch/pool_manager.ex
test/finch/http1/integration_proxy_test.exs
test/finch/http1/integration_test.exs
test/finch/http1/pool_test.exs
test/finch/http1/telemetry_test.exs
test/finch/http2/integration_test.exs
test/finch/http2/pool_test.exs
test/finch/http2/telemetry_test.exs
test/finch_test.exs

Follow-up to https://github.com/sneako/finch/pull/250.
Demo:
```elixir
Mix.install([
:req,
{:finch, github: "wojtekmach/finch", branch: "wm-alpn-followup", override: true},
:bandit
])
defmodule Main do
def main do
unless File.exists?("selfsigned.pem") do
File.write!("selfsigned.pem", """
-----BEGIN CERTIFICATE-----
MIICzjCCAbYCCQDM0i9xf9D8qTANBgkqhkiG9w0BAQsFADApMQswCQYDVQQGEwJJ
VDELMAkGA1UECAwCUk0xDTALBgNVBAcMBFJvbWUwHhcNMTcxMjI4MTAzMTE1WhcN
MTgxMjI4MTAzMTE1WjApMQswCQYDVQQGEwJJVDELMAkGA1UECAwCUk0xDTALBgNV
BAcMBFJvbWUwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQC6lBy3mpfB
UrtclV/PFOM8OGiBNYVZmNJmZqCZCl2LQE5ekPrJ2Fh+zkcJcO19OxmseN+2F7VT
zCYarty+h5ZXzNUmUcI2Ld60mfYwEfMjQRa4Tmp0K5PkphJ2gG9n9QOhFxky7KWz
C84oe7Zm8iGni6wAQEEBOdo/qTCfGbPHzd39WUV+9Aft8HeDUcnpMhO6vXWDT3Yh …
```

Deprecate :protocol in favour of :protocols

---

lib/finch.ex
lib/finch/http1/conn.ex
lib/finch/http1/pool.ex
lib/finch/http2/pool.ex
lib/finch/pool.ex
lib/finch/telemetry.ex
test/finch/http2/pool_test.exs
test/finch/http2/telemetry_test.exs

Recently, my team have adopted the practice of employing distinct finch instances for handling our requests. In this commit, we aim to include the pool-id/finch-instance-name in the telemetry metadata during request processing. This addition is particularly valuable for collecting statistics on a per-finch-instance basis.
This change aligns with both @aselder 's [request](https://github.com/sneako/finch/issues/199) and @oliveigah 's [PR](https://github.com/sneako/finch/pull/248), but it's a bit more concise. Hope this makes the review and merging process quicker.

Add finch instance name to telemetry metadata

---

.github/workflows/elixir.yml
lib/finch/http1/pool_metrics.ex
lib/finch/http2/pool_metrics.ex

We need to not use `when is_reference` since the `ref` is technically an opaque type and we break that by using `is_reference` (or at least that's what i'm reading into dialyzer's output)

fix types, appease dialyzer

---

README.md

👋 
This PR restores the logo size to the same 350px height as before [the dark/light mode change.](https://github.com/sneako/finch/commit/3c7fdb287523265a746a4b19039584cfa7c84f5c)

fix logo size

---

lib/finch.ex

Hello 👋 
First, thank you for your work on Finch 🙏
We encountered the following dyalixir error in our code:
```
lib/app/rpc.ex:352:no_return
Function post/2 has no local return.
```
Our function was only calling `Finch.build(...) |> Finch.resquest(...)` so nothing that could have raised. In this end, this was triggered because the `:request_timeout` keyword was missing from the `Finch.request_opt()` type.

fix: type Finch.request_opt() was missing the :request_timeout option

---

lib/finch.ex

Document there is no backpressure on HTTP2

---

lib/finch/http1/pool_metrics.ex
lib/finch/http2/pool.ex
lib/finch/pool_manager.ex
test/support/finch_case.ex

Fix typos and improve language

---

lib/finch.ex

I tried benchmarking this and it's inconclusive but I think conceptually it makes more sense.
{:ok, _} =
Bandit.start_link(
port: 4000,
plug: fn conn, _ ->
conn = Plug.Conn.send_chunked(conn, 200)
Enum.reduce(1..1000, conn, fn _, conn ->
{:ok, conn} = Plug.Conn.chunk(conn, String.duplicate("0", 1000))
conn
end)
end
)
{:ok, _} = Finch.start_link(name: :a)
{:ok, _} = Finch.start_link(name: :b)
req = Finch.build(:get, "http://localhost:4000")
Benchee.run(
%{
"a" => fn ->
fun = fn
{:status, value}, {_, headers, body, trailers} ->
{:cont, {value, headers, body, trailers}}
{:headers, value}, {status, headers, body, trailers} ->
{:cont, {status, headers ++ value, body, trailers}}
{:data, value}, {status, headers, body, trailers} ->
{:cont, {status, headers, [value | body], trailers}}
{:trailers, …

Finch.request/3: Use improper list and avoid Enum.reverse

---

lib/finch.ex

Hello there, the changes aim to resolve the following issue: #277 
```elixir
ArgumentError: unknown registry: Obfuscated.FinchPool
File "lib/registry.ex", line 1391, in Registry.info!/1
File "lib/registry.ex", line 1007, in Registry.register/3
File "lib/finch/http2/pool.ex", line 207, in Finch.HTTP2.Pool.init/1
File "gen_statem.erl", line 984, in :gen_statem.init_it/6
File "proc_lib.erl", line 241, in :proc_lib.init_p_do_apply/3
```
My comment here isn't correct – https://github.com/sneako/finch/issues/277#issuecomment-2265576904. The issue happens on shutdowns. 
---
The fix assumes that Supervisors shut down their children in reverse order. The problem with the current order is that `DynamicSupervisor` children use `Registry`. The registry goes down sooner than the dynamic supervisor …

Tweak Finch supervisor children strartup order

---

lib/finch.ex
lib/finch/http1/conn.ex
lib/finch/http1/pool.ex
lib/finch/http2/pool.ex
lib/finch/pool.ex
test/finch/http2/pool_test.exs
test/finch_test.exs

Currently `Finch.stream/5` and `Finch.stream_while/5` do not return accumulator in case of errors. If an error happens midway through streaming, there may be information in the accumulator that the user would like to access when handling the error.
This originally came up in https://github.com/wojtekmach/req/pull/435#discussion_r1853832157, where in the `{:status, 200}` handler we "open" collectable with `Collectable.into(collectable)` and put it in the accumulator. If the request fails, we want to call `collector.(:halt)`, however `collector` is only available in `acc`, and not returned on errors.
This changes the signatures as follows:
```diff
@spec stream(Request.t(), name(), acc, stream(acc), request_opts()) ::
-        {:ok, acc} | {:error, Exception.t()}
+        {:ok, acc} | …
```

Return acc when Finch.{stream,stream_while}/5 fails

---

lib/finch.ex
lib/finch/pool_manager.ex
test/finch_test.exs

This PR introduces `Finch.stop_pool/2`, which can be used to manually stop the connection pool of a given SHP.
We have tried it out in production, and it works fine, and it helped us fix our process leak.
See #294 for details.
It's worth noting that this function might not be enough. The client needs to make sure that no request to the given SHP is taking place while the pool is being stopped. This can actually be tricky. A simple solution of channeling all requests through a single process means that you can only have one req at a time to the given SHP, which might be a problem.
In our case we've implemented a basic reference counted GC mechanism, which tracks all the processes currently making a request to the given SHP. When there are no requests taking place anymore, the pool is …

Support manual pool termination

---

lib/finch/pool_manager.ex

Here's a PR that fixes https://github.com/sneako/finch/issues/305 if we decide that's a desirable change.

adds :supported_groups to list of tls options

---

lib/finch/http1/pool.ex

As mentioned on https://github.com/sneako/finch/pull/292, in order to facilitate pool state handling would be good to create a new struct instead of a tuple.

chore: refactor http1 pool state
